version: '2'
services:
  nlp:
    image: gswyhq/agriculture_knowledge_graph
#    build: .
    tty: true
    working_dir: "/Agriculture_KnowledgeGraph/demo"
    restart: always
    ports:
      - "8000:8000"
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      NEO4J_HOST: "neo4j"
      NEO4J_HTTP_PORT: 7474
      NEO4J_BOLT_PORT: 7687
    volumes:
      -  /etc/localtime:/etc/localtime
    networks:
      - mynet
    command: ["/bin/bash", "django_server_start.sh"]

  neo4j:
    image: gswyhq/neo4j_agriculture_knowledgegraph
    restart: always
    ports:
     - 7474:7474
     - 7687:7687
    environment:
      LANG: C.UTF-8
      NEO4J_dbms_allow__format__migration: "true"
      NEO4J_dbms_shell_enabled: "true"
      NEO4J_dbms_shell_host: "0.0.0.0"
      NEO4J_dbms_shell_port: 1337
      NEO4J_dbms_security_procedures_unrestricted: apoc.\\\*
      NEO4J_apoc_export_file_enabled: "true"
      TZ: "CST-8"
      NEO4J_dbms_memory_heap_initial__size: "4G"
      NEO4J_dbms_memory_heap_max__size: "4G"
      NEO4J_AUTH: "neo4j/123456"
    volumes:
       - /etc/localtime:/etc/localtime
    networks:
      - mynet

networks:
  mynet:
    driver: bridge


# ubuntu@ip$ docker-compose -f docker-compose.yml up -d